---
- name: Install Mysql
  hosts: ansible_mysql
  become: yes 

 
  tasks:

  - name: Install mysql-server 
    apt:
      name: mysql-server
      state: present

  - name: Install mysql-clent 
    apt:
      name: mysql-client
      state: present    

